### ISSUE TITLE
Exposing volumes

### ISSUE THREAD

**Issue by marcellodesales** [npm/npme-docker#5]
Hi there,

I have a few questions in regards to the current version of the Dockerfile.

1. Does the parent image from the Dockerfile expose volumes for the Redis and Couch servers? Given that this is running without exposing volumes, all data will be gone once the running container instance dies... 

2. The current version does not indicate where those are located. Do you use the default ones for each of the servers?

3. Why not using Fig and instantiating each of the servers separately and linking them together? That way, we can scale each of them individually if needed.

thanks!

**Comment by jkrems** [comment]
(Not one of the maintainers but just looked into similar questions)

* All files seem to be in `/etc/npme`
* The couch database (which is the important one) has its files in `/etc/npme/couchdb`
* The package tarballs are in `/etc/npme/packages` by default

It's possible to mount those directories as volumes when running the container, making backups relatively straight-forward.

**Comment by marcellodesales** [comment]
@jkrems Thanks for the notes... Yeah, I completely got NPME installed on RHEL 7 today! :+1:  Now I understand all of those directory structures! https://gist.github.com/marcellodesales/6a771a412a9e4aef6476

Yeah, I usually use a Data Container to mount the volumes and provide backups to our private Docker Registry... That way, it is definitely easier even to migrate the server to other locations! :)
