### ISSUE TITLE
problem with `npme update` on RHEL6.6

### ISSUE THREAD

**Issue by bcoe** [npm/npme-docker#6]
npmE update did not work on RHEL6, I got around the problem by using `npm install` instead in the dockerfile.

`RUN cd /etc/npme; npm install`

**Comment by silicondon** [comment]
@bcoe I believe I isolated the failure to the fact that the build occurs behind the firewall, and Docker build doesn't honor the proxy config settings in /etc/sysconfig/docker. Additionally, 'npm config set proxy ...' on the host was not taking.

Adding the following to the npme-docker Dockerfile and re-running the build did the trick:

RUN npm config set proxy http://<proxy>:<port> && \
    npm config set https-proxy http://<proxy>:<port> \
    npme update
