### ISSUE TITLE
UDP timeout on FROM: bcoe/npme

### ISSUE THREAD

**Issue by nathanjd** [npm/npme-docker#7]
I am having a problem downloading the base image for the container. Is this reproducible? Any help would be appreciated.

```
~/Projects/npme-docker (master)*$ docker build -t npme .
Sending build context to Docker daemon 24.36 MB
Sending build context to Docker daemon 
Step 0 : FROM bcoe/npme
Pulling repository bcoe/npme
INFO[0061] Get https://index.docker.io/v1/repositories/bcoe/npme/images: dial tcp: lookup index.docker.io on 10.1.82.144:53: read udp 10.1.82.144:53: i/o timeout 
```

**Comment by bcoe** [comment]
@nathanjd It looks like this issue might be related to the docker registry itself, perhaps try again in a few minutes and let me know if you continue being unable to download the image?

**Comment by nathanjd** [comment]
@bcoe It turns out the issue was with the OSX version of boot2docker. The following answer solved my issue.

http://stackoverflow.com/a/26804653

Thanks.
